import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import {Marketplace} from '../electron/marketplace.mjs';
import {validateCatalog,validatePackage} from '../electron/package-schema.mjs';
import {effectFrame,effectOptions} from '../electron/rgb-effects.mjs';
const manifest={schema:1,id:'test-widget',name:'Test widget',description:'A test extension',kind:'widget',author:'Nexus',version:'1.0.0',minNexus:'1.3.0',accent:'#a7e6c7',permissions:['storage'],content:{type:'sandbox',height:250,html:'<!doctype html><p>Version 1</p>'}};
function build(p=manifest){const bytes=Buffer.from(JSON.stringify(p));const {content,...entry}=p;return {bytes,catalog:{schema:1,packages:[{...entry,path:`packages/${p.id}/${p.version}.nexus.json`,size:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')}]}};}
async function setup(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'nexus-market-test-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));let served=build();let corrupt=false;const market=new Marketplace(root,'1.3.0',{fetcher:async url=>new Response(url.pathname.endsWith('catalog.json')?JSON.stringify(served.catalog):corrupt?'tampered':served.bytes)});await market.init();return {market,root,set:p=>served=build(p),corrupt:()=>corrupt=true};}
test('Store downloads and updates a package independently while preserving its data and dashboard identity',async t=>{const f=await setup(t);await f.market.refresh();await f.market.install(manifest.id);await f.market.data(manifest.id,{tasks:['Keep me']});f.set({...manifest,version:'1.0.1',content:{...manifest.content,html:'<p>Version 2</p>'}});await f.market.refresh();assert.equal(f.market.snapshot().packages[0].updateAvailable,true);await f.market.install(manifest.id);assert.equal(f.market.content(manifest.id).version,'1.0.1');assert.deepEqual(await f.market.data(manifest.id),{tasks:['Keep me']});const restart=new Marketplace(f.root,'1.3.0');await restart.init();assert.equal(restart.content(manifest.id).version,'1.0.1');assert.deepEqual(await restart.data(manifest.id),{tasks:['Keep me']});});
test('Checksum failure keeps the working version; failed refresh retains installed and cached catalog',async t=>{const f=await setup(t);await f.market.refresh();await f.market.install(manifest.id);f.set({...manifest,version:'1.0.1'});await f.market.refresh();f.corrupt();await assert.rejects(f.market.install(manifest.id),/Checksum/);assert.equal(f.market.content(manifest.id).version,'1.0.0');f.market.fetcher=async()=>{throw Error('offline');};await f.market.refresh();assert.equal(f.market.snapshot().status,'error');assert.equal(f.market.snapshot().installed.length,1);assert.equal(f.market.snapshot().packages.length,1);});
test('Uninstall is confined to the extension; data survives reinstall and storage permissions are enforced',async t=>{const f=await setup(t);await f.market.refresh();await f.market.install(manifest.id);await f.market.data(manifest.id,{keep:true});await assert.rejects(f.market.remove('../outside'));await f.market.remove(manifest.id);assert.equal(f.market.snapshot().installed.length,0);await assert.rejects(f.market.data(manifest.id));await f.market.install(manifest.id);assert.deepEqual(await f.market.data(manifest.id),{keep:true});await assert.rejects(f.market.data(manifest.id,'x'.repeat(70000)));});
test('Catalog rejects traversal, duplicate IDs, arbitrary downloads, missing hashes, privileged permissions and incompatible packages',async t=>{for(const patch of [{path:'../installer.exe'},{path:'https://example.com/a'},{sha256:''},{id:'../escape'},{permissions:['shell']}])assert.throws(()=>validateCatalog({schema:1,packages:[{...build().catalog.packages[0],...patch}]}));assert.throws(()=>validateCatalog({schema:1,packages:[...build().catalog.packages,...build().catalog.packages]}));assert.throws(()=>validatePackage({...manifest,content:{type:'shell',command:'calc.exe'}}));assert.throws(()=>validatePackage({...manifest,kind:'app',permissions:['web'],content:{type:'web',url:'file:///C:/Windows'}}));const f=await setup(t);f.set({...manifest,minNexus:'2.0.0'});await f.market.refresh();assert.equal(f.market.snapshot().packages[0].compatible,false);await assert.rejects(f.market.install(manifest.id),/2.0.0/);});
test('Rainbow varies across LEDs, cycle synchronizes LEDs, breathing varies over time and brightness limits all frames',()=>{const v=effectOptions({ids:['icue:0'],effect:'rainbow',color:'#ffffff',brightness:50,speed:50});const frame=effectFrame(v,12,0);assert.equal(frame.length,12);assert.ok(frame.some(c=>String(c)!==String(frame[0])));for(const c of frame)for(const x of c)assert.ok(x>=0&&x<=128);assert.deepEqual(effectFrame({...v,effect:'color-cycle'},2,300)[0],effectFrame({...v,effect:'color-cycle'},2,300)[1]);assert.notDeepEqual(effectFrame({...v,effect:'breathing'},1,0),effectFrame({...v,effect:'breathing'},1,1000));assert.deepEqual(effectFrame({...v,brightness:0},2,200),[[0,0,0],[0,0,0]]);assert.throws(()=>effectOptions({...v,speed:0}));assert.throws(()=>effectOptions({...v,effect:'shell'}));});
