import React, { useEffect, useRef, useState } from 'react';
import { Activity, ArrowDown, ArrowDownLeft, ArrowLeft, ArrowRight, ArrowUp, ArrowUpRight, Bell, Bluetooth, Check, ChevronDown, ChevronLeft, ChevronRight, Clock3, Cpu, Download, Expand, ExternalLink, Eye, Gamepad2, Globe, Grip, Headphones, LayoutDashboard, LayoutGrid, List, Maximize2, MessageCircle, Mic, MicOff, Minimize2, Minus, Monitor, Music2, Network, Pause, Play, Plus, Power, Radio, RefreshCw, Search, Settings2, ShieldCheck, SkipBack, SkipForward, SlidersHorizontal, Sparkles, Star, StickyNote, Timer, Trash2, Volume2, VolumeX, Waves, Wifi, X, Zap } from 'lucide-react';
import { api } from './api.js';
import { HardwarePage, RGBPage, RadioPage, RadioDock, useRadio } from './Extensions.jsx';

const profiles = { command: 'Command center', gaming: 'Gaming', focus: 'Focus' };
const widgetInfo = {
  radio: ['Internetradio', Radio, 'Livezenders, favorieten en je eigen audiostreams.'],
  welcome: ['Welkom', Sparkles, 'Je startpunt, recente game en snelle acties.'],
  system: ['Systeemprestaties', Activity, 'Live CPU, GPU en geheugengebruik.'],
  media: ['Now playing', Music2, 'Bedien je actieve Windows-mediaspeler.'],
  social: ['Connected spaces', MessageCircle, 'Discord, WhatsApp en Xbox binnen handbereik.'],
  library: ['Jouw games', Gamepad2, 'Start je favoriete en recent gespeelde games.'],
  audio: ['Audio control', SlidersHorizontal, 'Systeemvolume en microfoon rechtstreeks bedienen.'],
  network: ['Netwerk', Network, 'Live download- en uploadsnelheid.'],
  clock: ['Klok', Clock3, 'Tijd, datum en systeem-uptime.'],
  notes: ['Notities', StickyNote, 'Een plek voor wat je wilt onthouden.'],
  timer: ['Focustimer', Timer, 'Werk in sessies en neem op tijd een pauze.'],
  launchers: ['Launchpad', LayoutGrid, 'Al je gamelaunchers in één paneel.'],
};
const serviceIcons = { discord: Headphones, whatsapp: MessageCircle, spotify: Music2, xbox: Gamepad2 };
const sourceColors = { Steam: '#8fbde0', Epic: '#d4d7df', Xbox: '#83c97a', Rockstar: '#edbd58', Ubisoft: '#a49bec', EA: '#e8938e', GOG: '#c394d9', 'Battle.net': '#7fc4e0', Eigen: '#8dcbb9', Windows: '#82b8ee' };
const fmt = value => value == null ? '—' : Math.round(value);
const gb = n => n == null ? '—' : (n / 1024 ** 3).toFixed(1);
function speed(n) { if (n == null) return ['—', 'KB/s']; return n >= 1024 ** 2 ? [(n / 1024 ** 2).toFixed(1), 'MB/s'] : [(n / 1024).toFixed(0), 'KB/s']; }
const mmss = seconds => `${Math.floor(Math.max(0, seconds) / 60).toString().padStart(2, '0')}:${Math.floor(Math.max(0, seconds) % 60).toString().padStart(2, '0')}`;
function useNow() { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []); return now; }
function IconButton({ icon: Icon, label, onClick, className = '', ...rest }) { return <button title={label} aria-label={label} onClick={onClick} className={`icon-button ${className}`} {...rest}><Icon size={17} strokeWidth={1.7} /></button>; }
function Brand({ small = false }) { return <div className={`brand ${small ? 'small' : ''}`}><span className="brand-symbol"><span /><span /><span /></span>{!small && <span>NEXUS<span className="brand-hub">HUB</span></span>}</div>; }
function Sparkline({ data = [], color = 'var(--accent)', filled = true }) {
  const values = data.length ? data : [0, 0];
  const ceiling = Math.max(10, ...values);
  const points = values.map((n, i) => `${i / Math.max(1, values.length - 1) * 260},${52 - n / ceiling * 45}`).join(' ');
  return <svg className="sparkline" viewBox="0 0 260 58" preserveAspectRatio="none" aria-hidden="true">{filled && <polygon points={`0,58 ${points} 260,58`} fill={color} opacity=".07" />}<polyline points={points} fill="none" stroke={color} strokeWidth="1.8" vectorEffect="non-scaling-stroke" /></svg>;
}
function AppMark({ id, name, color, size = '' }) { const Icon = serviceIcons[id] || Gamepad2; return <span className={`app-mark ${size}`} style={{ '--service-color': color || sourceColors[name] || 'var(--accent)' }}><Icon size={size === 'large' ? 27 : 21} strokeWidth={1.7} /></span>; }

export default function App() {
  const [state, setState] = useState(null), [metrics, setMetrics] = useState({}), [history, setHistory] = useState({ cpu: [], gpu: [], ram: [], down: [], up: [] });
  const [page, setPage] = useState('dashboard'), [edit, setEdit] = useState(false), [modal, setModal] = useState(null), [toast, setToast] = useState(null), [search, setSearch] = useState(''), [serviceStatus, setServiceStatus] = useState({});
  const player = useRadio();
  const now = useNow(); const toastTimer = useRef();
  const notify = (text, error = false) => { clearTimeout(toastTimer.current); setToast({ text, error }); toastTimer.current = setTimeout(() => setToast(null), error ? 6500 : 3500); };
  const run = async (fn, success) => { try { const result = await fn(); if (success) notify(success); return result; } catch (error) { notify(error.message.replace(/^Error invoking remote method '[^']+': Error: /, ''), true); } };
  useEffect(() => {
    api.bootstrap().then(data => { setState(data.state); setMetrics(data.metrics); }).catch(error => notify(error.message, true));
    const offState = api.onState(setState);
    const offMetrics = api.onMetrics(data => {
      setMetrics(data);
      setHistory(old => ({ cpu: [...old.cpu, data.cpu || 0].slice(-45), gpu: data.gpu?.usage != null ? [...old.gpu, data.gpu.usage].slice(-45) : [], ram: [...old.ram, data.ramTotal ? data.ramUsed / data.ramTotal * 100 : 0].slice(-45), down: [...old.down, data.network?.download || 0].slice(-45), up: [...old.up, data.network?.upload || 0].slice(-45) }));
    });
    const offService = api.onService(data => setServiceStatus(old => ({ ...old, [data.id]: { ...old[data.id], ...data } })));
    const offShortcut = api.onShortcut(action => { if (action === 'search') setModal('search'); });
    return () => { offState(); offMetrics(); offService(); offShortcut(); clearTimeout(toastTimer.current); };
  }, []);
  useEffect(() => {
    const listener = e => {
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); setModal(old => old === 'search' ? null : 'search'); }
      if (e.key === 'Escape') { setModal(null); setEdit(false); run(() => api.window('exit-fullscreen')); }
      if (e.key === 'F11') { e.preventDefault(); run(() => api.window('fullscreen')); }
    };
    window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener);
  }, []);
  const navigate = next => { run(() => api.service('hide')); setPage(next); setSearch(''); setModal(null); setEdit(false); };
  useEffect(() => { if (state?.overlay) navigate('dashboard'); }, [state?.overlay]);
  useEffect(() => {
    const embedded = page !== 'xbox' && (state?.services?.[page] || state?.webWidgets.some(w => w.id === page));
    if (embedded) run(() => modal ? api.service('hide') : api.service('open', page));
  }, [modal]);
  if (!state) return <div className="boot"><Brand /><span>Je command center wordt klaargezet…</span></div>;
  const { settings, library, favorites } = state;
  const layout = state.layouts[settings.profile] || [];
  const service = state.services[page] || state.webWidgets.find(w => w.id === page);
  const date = new Date(now);
  const gameLaunch = game => run(() => api.launchGame(game.id), `${game.name} wordt gestart`);
  const changeSettings = value => run(() => api.settings(value));
  const updateLayout = next => run(() => api.layout(settings.profile, next));
  const moveWidget = (id, shift) => { const next = [...layout], i = next.indexOf(id), j = i + shift; if (j >= 0 && j < next.length) { [next[i], next[j]] = [next[j], next[i]]; updateLayout(next); } };
  const goService = id => { navigate(id); setServiceStatus(old => ({ ...old, [id]: { loading: true } })); };
  const context = { player, state, metrics, history, now, run, notify, navigate, gameLaunch, goService, setModal, changeSettings };
  return <div className={`app theme-${settings.theme} density-${settings.density} ${settings.reduceMotion ? 'reduce-motion' : ''} ${state.overlay ? 'is-overlay' : ''}`}>
    <aside className="sidebar"><button className="brand-button" aria-label="Nexus dashboard" onClick={() => navigate('dashboard')}><Brand small /></button><div className="nav-main">
      <Nav icon={LayoutDashboard} label="Dashboard" active={page === 'dashboard'} onClick={() => navigate('dashboard')} />
      <Nav icon={Gamepad2} label="Gamebibliotheek" active={page === 'library'} onClick={() => navigate('library')} />
      <Nav icon={LayoutGrid} label="Apps & verbindingen" active={page === 'apps'} onClick={() => navigate('apps')} />
      <Nav icon={Activity} label="Systeemprestaties" active={page === 'hardware'} onClick={() => navigate('hardware')} />
      <Nav icon={Sparkles} label="RGB-verlichting" active={page === 'rgb'} onClick={() => navigate('rgb')} />
      <Nav icon={Radio} label="Internetradio" active={page === 'radio'} onClick={() => navigate('radio')} />
      <span className="nav-divider" />
      {Object.entries(state.services).map(([id, item]) => <Nav key={id} icon={serviceIcons[id]} label={item.name} active={page === id} onClick={() => goService(id)} color={item.color} />)}
    </div><div className="nav-bottom"><Nav icon={Settings2} label="Instellingen" active={page === 'settings'} onClick={() => navigate('settings')} /><div className="avatar" title="Lokaal profiel">{(settings.username || 'N').slice(0, 1).toUpperCase()}<i /></div></div></aside>
    <div className="main-shell">
      <header className="topbar"><div className="topbar-brand"><Brand /><span className="version">PERSONAL COMMAND CENTER</span></div>
        <div className="topbar-right"><span className="local-status"><i className="status-dot" /> Lokaal verbonden</span><button className="search-trigger" onClick={() => setModal('search')}><Search size={15} /><span>Zoeken</span><kbd>Ctrl K</kbd></button></div>
      </header>
      <main className={`main-content ${service ? 'service-content' : ''}`}>
        {page === 'dashboard' && <>
          <div className="page-heading"><div><div className="eyebrow"><span className="tiny-line" /> JOUW SETUP. JOUW RUIMTE.</div><h1>Alles onder controle<span className="accent">.</span></h1><p>Je games, je mensen, je muziek. Samen op één scherm.</p></div><div className="heading-actions"><label className="profile-select"><span className="status-dot" /><select aria-label="Dashboardprofiel" value={settings.profile} onChange={e => changeSettings({ profile: e.target.value })}>{Object.entries(profiles).map(([id, text]) => <option value={id} key={id}>{text}</option>)}</select><ChevronDown size={14} /></label><button className={`button secondary ${edit ? 'selected' : ''}`} onClick={() => setEdit(!edit)}>{edit ? <Check size={16} /> : <SlidersHorizontal size={16} />}<span>{edit ? 'Klaar' : 'Aanpassen'}</span></button><button className="button primary" onClick={() => setModal('widgets')}><Plus size={16} /><span>Widget</span></button></div></div>
          {state.preview && <div className="preview-banner"><Monitor size={17} /> Vormgevingspreview · Open de desktopapp voor live hardware, games en appvensters.</div>}
          {edit && <div className="edit-banner"><Grip size={17} /><span>Sleep widgets naar een nieuwe plek. Gebruik de pijlen op een touchscreen.</span><button onClick={() => setModal('widgets')}>Widgets beheren <ArrowRight size={14} /></button></div>}
          <div className={`dashboard-grid ${edit ? 'editing' : ''}`}>{layout.map((id, index) => {
            const title = widgetInfo[id]?.[0] || state.webWidgets.find(w => w.id === id)?.name || 'Widget';
            const wide = state.sizes[id] === 'wide' || (state.sizes[id] !== 'normal' && ['welcome', 'system', 'library'].includes(id));
            return <section key={id} className={`widget widget-${id.startsWith('web-') ? 'web' : id} ${wide ? 'span-2' : ''}`} draggable={edit} onDragStart={e => { e.dataTransfer.setData('text/nexus-widget', id); e.dataTransfer.effectAllowed = 'move'; }} onDragOver={e => { if (edit) e.preventDefault(); }} onDrop={e => { e.preventDefault(); const source = e.dataTransfer.getData('text/nexus-widget'); if (!layout.includes(source) || source === id) return; const next = layout.filter(w => w !== source); next.splice(next.indexOf(id), 0, source); updateLayout(next); }}>
              {edit && <div className="widget-edit"><span><Grip size={14} />{title}</span><div><IconButton icon={ChevronLeft} label={`${title} naar links`} disabled={index === 0} onClick={() => moveWidget(id, -1)} /><IconButton icon={ChevronRight} label={`${title} naar rechts`} disabled={index === layout.length - 1} onClick={() => moveWidget(id, 1)} /><IconButton icon={Expand} label={`Breedte van ${title} wijzigen`} onClick={() => run(() => api.layout(settings.profile, layout, { [id]: wide ? 'normal' : 'wide' }))} /><IconButton icon={X} label={`${title} verbergen`} onClick={() => updateLayout(layout.filter(w => w !== id))} /></div></div>}
              <Widget id={id} {...context} />
            </section>;
          })}</div>
          {!layout.length && <Empty icon={LayoutGrid} title="Maak deze ruimte van jou" text="Voeg je eerste widgets toe en stel je dashboard samen." action="Widget toevoegen" onClick={() => setModal('widgets')} />}
        </>}
        {page === 'library' && <Library {...context} search={search} setSearch={setSearch} />}
        {page === 'apps' && <Apps {...context} />}
        {page === 'hardware' && <HardwarePage {...context} />}
        {page === 'rgb' && <RGBPage {...context} />}
        {page === 'radio' && <RadioPage {...context} player={player} />}
        {page === 'settings' && <Settings {...context} />}
        {service && (service.native ? <NativeServicePage key={page} id={page} definition={service} status={serviceStatus[page]} {...context} /> : <ServicePage key={page} id={page} definition={service} status={serviceStatus[page]} {...context} />)}
      </main>
      <footer className="statusbar"><span><i className={`status-dot ${metrics.nativeReady ? '' : 'neutral'}`} />{state.preview ? 'Browserpreview' : metrics.nativeReady ? 'Windows bridge online' : 'Windows verbinden…'}<span className="footer-separator">/</span>{profiles[settings.profile]}</span><span className="footer-center">{library.scanning ? <><RefreshCw size={11} className="spin" /> Games zoeken…</> : `${library.games.length} games in je bibliotheek`}</span><span><Monitor size={12} />{state.overlay ? 'Overlay' : state.displayTarget?.label || state.displays.find(d => d.id === settings.displayId)?.label || 'Desktop'}<span className="footer-separator">/</span>{date.toLocaleTimeString('nl-NL', { hour: '2-digit', minute: '2-digit' })}</span></footer>
    </div>
    {!service && <RadioDock player={player} onOpen={() => navigate('radio')} />}
    {toast && <div className={`toast ${toast.error ? 'error' : ''}`} role="status">{toast.error ? <Bell size={18} /> : <Check size={18} />}<span>{toast.text}</span><button aria-label="Melding sluiten" onClick={() => setToast(null)}><X size={16} /></button></div>}
    {modal && <Modal title={modal === 'widgets' ? 'Maak ruimte voor wat telt' : modal === 'add-game' ? 'Voeg een game toe' : 'Zoek in je command center'} onClose={() => setModal(null)} wide={modal === 'widgets'}>
      {modal === 'widgets' && <WidgetPicker {...context} layout={layout} updateLayout={updateLayout} />}
      {modal === 'add-game' && <AddGame {...context} />}
      {modal === 'search' && <CommandSearch {...context} />}
    </Modal>}
  </div>;
}
function Nav({ icon: Icon, label, active, onClick, color }) { return <button className={`nav-item ${active ? 'active' : ''}`} title={label} aria-label={label} aria-current={active ? 'page' : undefined} onClick={onClick} style={color ? { '--nav-color': color } : {}}><Icon size={21} strokeWidth={1.6} /><span className="nav-tooltip">{label}</span></button>; }
function WidgetHeader({ icon: Icon, title, children }) { return <div className="widget-header"><h2><Icon size={15} strokeWidth={1.6} />{title}</h2>{children}</div>; }
function Empty({ icon: Icon, title, text, action, onClick, compact = false }) { return <div className={`empty ${compact ? 'compact' : ''}`}><span className="empty-icon"><Icon size={compact ? 25 : 32} strokeWidth={1.3} /></span><h3>{title}</h3><p>{text}</p>{action && <button className="button secondary" onClick={onClick}>{action}<ArrowUpRight size={15} /></button>}</div>; }

function Widget({ id, ...ctx }) {
  const { state, metrics, history, now, run, navigate, goService, gameLaunch, setModal } = ctx;
  const { library, settings, favorites } = state;
  if (id === 'welcome') {
    const hour = new Date(now).getHours(); const greeting = hour < 12 ? 'Goedemorgen' : hour < 18 ? 'Goedemiddag' : 'Goedenavond';
    const recent = library.games.find(g => g.id === state.recent[0]?.id);
    return <div className="welcome-body"><div className="welcome-orbit"><div /><div /><div /><span className="orbital-dot" /></div><div className="welcome-content"><span className="pill subtle"><span className="status-dot" /> ALL SYSTEMS, ONE SPACE</span><h2>{greeting}{settings.username ? `, ${settings.username}` : ''}<span className="accent">.</span></h2><p>Even opladen. Dan weer door.</p><div className="welcome-actions"><button className="button primary" onClick={() => recent ? gameLaunch(recent) : navigate('library')}><Play size={14} fill="currentColor" />{recent ? 'Verder spelen' : 'Open je bibliotheek'}</button><button className="button ghost" onClick={() => run(() => api.window('overlay'))}>Overlay<ArrowUpRight size={15} /></button></div>{recent && <div className="last-played">LAATST GESTART <span>{recent.name}</span></div>}</div><span className="welcome-watermark">N</span></div>;
  }
  if (id === 'system') return <><WidgetHeader icon={Activity} title="Systeemprestaties"><span className="live-label"><i />LIVE</span></WidgetHeader><div className="system-metrics"><Metric name="CPU" value={fmt(metrics.cpu)} unit="%" subtitle={metrics.cpuName?.replace(/\(R\)|\(TM\)|CPU|Processor|\d+-Core/gi, '').trim() || 'Wachten op Windows'} data={history.cpu} color="var(--accent)" /><Metric name="GPU" value={fmt(metrics.gpu?.usage)} unit="%" subtitle={metrics.gpu?.name || 'Grafische processor'} data={history.gpu} color="#a797ec" detail={metrics.gpu?.temperature != null ? `${metrics.gpu.temperature}°C` : 'Sensor niet beschikbaar'} /><Metric name="RAM" value={metrics.ramTotal ? fmt(metrics.ramUsed / metrics.ramTotal * 100) : '—'} unit="%" subtitle={`${gb(metrics.ramUsed)} / ${gb(metrics.ramTotal)} GB`} data={history.ram} color="#74b7e3" /></div><div className="system-bottom"><span><Cpu size={12} />{metrics.cores ? `${metrics.cores} logische cores` : 'Native monitoring'}</span><button className="system-sensors-link" onClick={() => navigate('hardware')}>{metrics.gpu?.temperature != null ? `${metrics.gpu.temperature}°C · ` : ''}Alle sensoren<ArrowRight size={12} /></button></div></>;
  if (id === 'media') {
    const media = metrics.media;
    return <><WidgetHeader icon={Music2} title="Now playing"><button className="service-link" title="Spotify openen" onClick={() => goService('spotify')}><Music2 size={14} />Spotify<ArrowUpRight size={12} /></button></WidgetHeader><div className={`album-art ${media?.playing ? 'playing' : ''}`}><div className="album-grid" /><div className="vinyl"><div className="vinyl-center"><Waves size={25} /></div></div><span className="album-caption">NEXUS FREQUENCIES</span><span className="album-tag">{media?.source?.toLowerCase().includes('spotify') ? 'SPOTIFY' : 'WINDOWS MEDIA'}</span></div><div className="track-info"><div><h3 title={media?.title}>{media?.title || 'Jouw soundtrack begint hier'}</h3><p>{media?.artist || 'Open Spotify en speel iets af'}</p></div>{media?.playing && <div className="equalizer"><i /><i /><i /><i /></div>}</div><div className="track-progress"><div style={{ width: `${media?.duration ? Math.min(100, media.position / media.duration * 100) : 0}%` }} /></div><div className="track-times"><span>{mmss(media?.position || 0)}</span><span>{mmss(media?.duration || 0)}</span></div><div className="media-controls"><IconButton icon={SkipBack} label="Vorige track" disabled={!media?.canPrevious} onClick={() => run(() => api.media('previous'))} /><IconButton icon={media?.playing ? Pause : Play} label={media?.playing ? 'Pauzeren' : 'Afspelen'} className="play-button" disabled={!media?.canPlay} onClick={() => run(() => api.media('toggle'))} /><IconButton icon={SkipForward} label="Volgende track" disabled={!media?.canNext} onClick={() => run(() => api.media('next'))} /></div></>;
  }
  if (id === 'social') return <><WidgetHeader icon={MessageCircle} title="Connected spaces"><span className="caption">JOUW APPS</span></WidgetHeader><div className="social-list">{['discord', 'whatsapp', 'xbox'].map(key => { const s = state.services[key]; return <button key={key} className="social-row" onClick={() => goService(key)}><AppMark id={key} color={s.color} /><span><strong>{s.name}</strong><small>{key === 'discord' ? 'Je servers, chats en voice' : key === 'whatsapp' ? 'Je gesprekken, dichtbij' : 'Cloud gaming & je Xbox-account'}</small></span><ArrowUpRight size={16} /></button>; })}</div><div className="social-note"><ShieldCheck size={13} /><span>Je eigen accounts. Veilig gescheiden.</span></div></>;
  if (id === 'library') {
    const picked = [...library.games].sort((a, b) => Number(favorites.includes(b.id)) - Number(favorites.includes(a.id)) || (state.recent.findIndex(r => r.id === a.id) === -1 ? 999 : state.recent.findIndex(r => r.id === a.id)) - (state.recent.findIndex(r => r.id === b.id) === -1 ? 999 : state.recent.findIndex(r => r.id === b.id))).slice(0, 4);
    return <><WidgetHeader icon={Gamepad2} title="Klaar voor de volgende sessie"><button className="text-link" onClick={() => navigate('library')}>Alle games <ArrowRight size={14} /></button></WidgetHeader>{picked.length ? <div className="mini-games">{picked.map(g => <GameCard key={g.id} game={g} favorite={favorites.includes(g.id)} artwork={settings.artwork} onPlay={() => gameLaunch(g)} onFavorite={() => run(() => api.favorite(g.id))} small />)}</div> : <Empty compact icon={Gamepad2} title={library.scanning ? 'Je games verzamelen…' : 'Een plek voor al je games'} text={library.scanning ? 'Steam, Xbox, Epic en je andere installaties worden doorzocht.' : 'Scan je pc of voeg een game toe om te beginnen.'} action={library.scanning ? null : 'Bibliotheek openen'} onClick={() => navigate('library')} />}</>;
  }
  if (id === 'radio') return <><WidgetHeader icon={Radio} title="Internetradio"><button className="text-link" onClick={() => navigate('radio')}>Zenders<ArrowRight size={14} /></button></WidgetHeader><div className="radio-widget-body"><Radio size={35} /><h3>{ctx.player.current?.name || 'Vind je frequentie'}</h3><p>{ctx.player.playing ? 'Live radio speelt' : 'Je favoriete stations binnen handbereik'}</p><button className="button secondary" onClick={() => ctx.player.current ? ctx.player.toggle() : navigate('radio')}>{ctx.player.playing ? 'Pauzeren' : 'Luisteren'}</button></div></>;
  if (id === 'audio') return <AudioWidget {...ctx} />;
  if (id === 'network') {
    const [down, downUnit] = speed(metrics.network?.download), [up, upUnit] = speed(metrics.network?.upload);
    return <><WidgetHeader icon={Network} title="Netwerk"><span className={`live-label ${metrics.network?.connected ? '' : 'offline'}`}><i />{metrics.network?.connected ? 'VERBONDEN' : 'WACHTEN'}</span></WidgetHeader><div className="network-values"><div><span><ArrowDown size={13} />Download</span><strong>{down}<small>{downUnit}</small></strong></div><div><span><ArrowUp size={13} />Upload</span><strong>{up}<small>{upUnit}</small></strong></div></div><div className="network-chart"><Sparkline data={history.down} /><Sparkline data={history.up} color="#a797ec" filled={false} /></div><div className="network-footer"><Wifi size={12} /><span>{metrics.network?.name || 'Windows-netwerk'}</span><span>LIVE VERKEER</span></div></>;
  }
  if (id === 'clock') { const date = new Date(now); return <><WidgetHeader icon={Clock3} title="Hier & nu"><span className="caption">{Intl.DateTimeFormat().resolvedOptions().timeZone.split('/').pop()}</span></WidgetHeader><div className="clock-body"><span className="clock-date">{date.toLocaleDateString('nl-NL', { weekday: 'long' })}</span><div className="clock-digits">{date.toLocaleTimeString('nl-NL', { hour: '2-digit', minute: '2-digit' })}<span>{date.getSeconds().toString().padStart(2, '0')}</span></div><p>{date.toLocaleDateString('nl-NL', { day: 'numeric', month: 'long', year: 'numeric' })}</p></div><div className="clock-footer"><span className="status-dot" />{metrics.uptime ? `Je pc is ${Math.floor(metrics.uptime / 3600)}u ${Math.floor(metrics.uptime % 3600 / 60)}m actief` : 'Een goed moment om te beginnen'}</div></>; }
  if (id === 'notes') return <NotesWidget {...ctx} />;
  if (id === 'timer') return <TimerWidget {...ctx} />;
  if (id === 'launchers') return <><WidgetHeader icon={LayoutGrid} title="Launchpad"><span className="caption">QUICK ACCESS</span></WidgetHeader><div className="launcher-grid">{Object.keys(state.launchers).map(name => <button key={name} title={`${name} openen`} onClick={() => run(() => api.launcher(name))}><span style={{ color: sourceColors[name] }}><Gamepad2 size={22} strokeWidth={1.4} /></span><small>{name}</small></button>)}</div></>;
  const web = state.webWidgets.find(w => w.id === id);
  return web ? <><WidgetHeader icon={Globe} title={web.name} /><div className="web-widget"><Globe size={34} strokeWidth={1} /><h3>{web.name}</h3><p>{new URL(web.url).hostname}</p><button className="button secondary" onClick={() => goService(id)}>Open in Nexus <ArrowUpRight size={15} /></button></div></> : null;
}
function Metric({ name, value, unit, subtitle, data, color, detail }) { return <div className="metric" style={{ '--metric-color': color }}><div className="metric-name"><i />{name}<span>{name === 'CPU' ? 'PROCESSOR' : name === 'GPU' ? 'GRAPHICS' : 'MEMORY'}</span></div><div className="metric-value">{value}<span>{unit}</span></div><div className="metric-subtitle" title={subtitle}>{subtitle}</div><div className="metric-graph">{data.length ? <Sparkline data={data} color={color} /> : <div className="sensor-placeholder"><span />{detail || 'Wachten op gegevens'}</div>}</div></div>; }
function AudioWidget({ metrics, run }) {
  const [volume, setVolume] = useState(0), [dragging, setDragging] = useState(false);
  useEffect(() => { if (!dragging) setVolume(metrics.audio?.volume ?? 0); }, [metrics.audio?.volume, dragging]);
  const available = metrics.audio?.available;
  const commit = () => { setDragging(false); run(() => api.audio('volume', volume)); };
  return <><WidgetHeader icon={SlidersHorizontal} title="Audio control"><IconButton icon={Settings2} label="Windows-geluidsinstellingen" onClick={() => run(() => api.window('sound-settings'))} /></WidgetHeader><div className="audio-output"><div><span className="audio-symbol"><Headphones size={20} /></span><span><strong>Standaarduitvoer</strong><small>Windows-systeemaudio</small></span></div><strong>{available ? `${volume}%` : '—'}</strong></div><div className="volume-row"><IconButton icon={metrics.audio?.muted ? VolumeX : Volume2} label={metrics.audio?.muted ? 'Geluid inschakelen' : 'Geluid dempen'} disabled={!available} onClick={() => run(() => api.audio('mute', !metrics.audio?.muted))} /><input aria-label="Systeemvolume" type="range" min="0" max="100" value={volume} disabled={!available} style={{ '--range': `${volume}%` }} onPointerDown={() => setDragging(true)} onChange={e => setVolume(+e.target.value)} onPointerUp={commit} onKeyUp={commit} onPointerCancel={() => setDragging(false)} /></div><button className={`mic-toggle ${metrics.mic?.muted ? 'muted' : ''}`} disabled={!metrics.mic?.available} onClick={() => run(() => api.audio('mic', !metrics.mic?.muted))}><span>{metrics.mic?.muted ? <MicOff size={18} /> : <Mic size={18} />}<span>Microfoon<small>{!metrics.mic?.available ? 'Niet beschikbaar' : metrics.mic?.muted ? 'Gedempt' : 'Ingeschakeld'}</small></span></span><span className={`toggle ${metrics.mic?.available && !metrics.mic?.muted ? 'on' : ''}`} /></button></>;
}
function NotesWidget({ state, run }) {
  const [text, setText] = useState(state.notes), [status, setStatus] = useState('Lokaal opgeslagen'); const pending = useRef();
  useEffect(() => () => clearTimeout(pending.current), []);
  const change = value => { setText(value); setStatus('Opslaan…'); clearTimeout(pending.current); pending.current = setTimeout(async () => { const saved = await run(() => api.notes(value)); setStatus(saved ? 'Lokaal opgeslagen' : 'Opslaan mislukt'); }, 450); };
  return <><WidgetHeader icon={StickyNote} title="Even onthouden"><span className="caption">PRIVÉ</span></WidgetHeader><textarea className="notes-input" aria-label="Notities" placeholder="Een idee. Een reminder. Je volgende avontuur…" value={text} maxLength={20000} onChange={e => change(e.target.value)} onBlur={() => { clearTimeout(pending.current); run(() => api.notes(text)).then(saved => setStatus(saved ? 'Lokaal opgeslagen' : 'Opslaan mislukt')); }} /><div className="notes-footer"><ShieldCheck size={12} />{status}<span>{text.length} tekens</span></div></>;
}
function TimerWidget({ state, now, run }) {
  const t = state.timer; const remaining = t.endsAt ? Math.min(t.duration, Math.max(0, Math.ceil((t.endsAt - now) / 1000))) : t.remaining;
  const update = value => run(() => api.timer(value));
  return <><WidgetHeader icon={Timer} title="Focus session"><span className="caption">{t.endsAt ? 'IN JE FLOW' : 'MAAK TIJD'}</span></WidgetHeader><div className={`timer-ring ${t.endsAt ? 'active' : ''}`} style={{ '--progress': `${Math.min(100, remaining / t.duration * 100)}%` }}><div><strong>{mmss(remaining)}</strong><span>{remaining === 0 ? 'Goed gedaan.' : t.endsAt ? 'Eén ding tegelijk.' : 'Ruimte om te focussen.'}</span></div></div><div className="timer-presets">{[15, 25, 45].map(min => <button key={min} className={t.duration === min * 60 ? 'active' : ''} onClick={() => update({ duration: min * 60, remaining: min * 60, running: false })}>{min} min</button>)}</div><div className="timer-controls"><button className="button primary" onClick={() => update({ duration: t.duration, remaining: remaining || t.duration, running: !t.endsAt })}>{t.endsAt ? <Pause size={15} /> : <Play size={15} />}{t.endsAt ? 'Pauze' : 'Start focus'}</button><IconButton icon={RefreshCw} label="Timer opnieuw instellen" onClick={() => update({ duration: t.duration, remaining: t.duration, running: false })} /></div></>;
}

function GameCard({ game, favorite, artwork, onPlay, onFavorite, small, onRemove }) {
  const [failed, setFailed] = useState(false); useEffect(() => setFailed(false), [game.artwork]); const color = sourceColors[game.source] || '#8dcbb9';
  const initials = game.name.split(/\s+/).filter(Boolean).map(w => w[0]).slice(0, 3).join('').toUpperCase();
  return <div className={`game-card ${small ? 'small' : ''}`} style={{ '--game-color': color }}><button className="game-art" aria-label={`${game.name} starten`} onClick={onPlay}>{artwork && game.artwork && !failed ? <img src={game.artwork} alt="" loading="lazy" onError={() => setFailed(true)} /> : <div className="game-generated-art"><div className="game-art-orbit" /><span className="game-initials">{initials}</span><Gamepad2 size={small ? 25 : 38} strokeWidth={.8} /><span className="game-cover-title">{game.name}</span></div>}<span className="game-source">{game.source}</span><span className="game-play"><Play size={19} fill="currentColor" /></span></button><button className="game-cover-edit" aria-label={`Hoes voor ${game.name} kiezen`} onClick={() => api.chooseCover(game.id).catch(error => alert(error.message))}>Hoes kiezen</button><button className={`favorite-button ${favorite ? 'favorited' : ''}`} aria-label={`${game.name} ${favorite ? 'uit favorieten verwijderen' : 'favoriet maken'}`} title="Favoriet" onClick={onFavorite}><Star size={14} fill={favorite ? 'currentColor' : 'none'} /></button><div className="game-card-info"><button onClick={onPlay} title={game.name}>{game.name}</button><span><i />Geïnstalleerd{onRemove && <button className="remove-game" title="Uit Nexus verwijderen" aria-label={`${game.name} uit Nexus verwijderen`} onClick={onRemove}><X size={12} /></button>}</span></div></div>;
}
function Library(ctx) {
  const { state, search, setSearch, run, gameLaunch, setModal } = ctx;
  const [source, setSource] = useState('Alle'), [onlyFavorites, setOnlyFavorites] = useState(false), [sort, setSort] = useState('name'), [list, setList] = useState(false);
  const sources = [...new Set(state.library.games.map(g => g.source))].sort();
  const games = state.library.games.filter(g => (source === 'Alle' || g.source === source) && (!onlyFavorites || state.favorites.includes(g.id)) && g.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a, b) => sort === 'recent' ? (state.recent.find(r => r.id === b.id)?.at || 0) - (state.recent.find(r => r.id === a.id)?.at || 0) : a.name.localeCompare(b.name));
  return <><div className="page-heading"><div><div className="eyebrow"><span className="tiny-line" /> ONE LIBRARY. EVERY WORLD.</div><h1>Je volgende avontuur<span className="accent">.</span></h1><p>{state.library.games.length} games, {sources.length} platforms. Eén plek om te beginnen.</p></div><div className="heading-actions"><button className="button secondary" disabled={state.library.scanning} onClick={() => run(() => api.scanGames(), 'Bibliotheek bijgewerkt')}><RefreshCw size={16} className={state.library.scanning ? 'spin' : ''} />{state.library.scanning ? 'Scannen…' : 'Games scannen'}</button><button className="button primary" onClick={() => setModal('add-game')}><Plus size={16} />Game toevoegen</button></div></div>
    <div className="library-toolbar"><label className="input-search"><Search size={17} /><input aria-label="Games zoeken" placeholder="Zoek een game…" value={search} onChange={e => setSearch(e.target.value)} /><kbd>/</kbd></label><button className={`button secondary ${onlyFavorites ? 'selected' : ''}`} onClick={() => setOnlyFavorites(!onlyFavorites)}><Star size={15} fill={onlyFavorites ? 'currentColor' : 'none'} />Favorieten</button><select aria-label="Games sorteren" className="select" value={sort} onChange={e => setSort(e.target.value)}><option value="name">Naam A–Z</option><option value="recent">Laatst gestart</option></select><div className="segmented"><IconButton icon={LayoutGrid} label="Rasterweergave" className={!list ? 'active' : ''} onClick={() => setList(false)} /><IconButton icon={List} label="Lijstweergave" className={list ? 'active' : ''} onClick={() => setList(true)} /></div></div>
    <div className="source-tabs">{['Alle', ...sources].map(s => <button key={s} className={source === s ? 'active' : ''} onClick={() => setSource(s)}>{s}<span>{state.library.games.filter(g => s === 'Alle' || g.source === s).length}</span></button>)}</div>
    {state.library.warnings?.map(w => <div key={w} className="info-banner"><Bell size={15} />{w}</div>)}
    {games.length ? <div className={list ? 'game-list' : 'game-library-grid'}>{games.map(g => list ? <div className="game-list-row" key={g.id}><>{g.artwork && state.settings.artwork ? <img className="game-list-cover" src={g.artwork} alt="" /> : <AppMark name={g.source} />}</><div><strong>{g.name}</strong><small>{g.source} · Geïnstalleerd</small></div><IconButton icon={Star} label={`${g.name} favoriet`} className={state.favorites.includes(g.id) ? 'accent' : ''} onClick={() => run(() => api.favorite(g.id))} /><button className="button secondary" onClick={() => gameLaunch(g)}><Play size={14} />Starten</button>{g.custom && <IconButton icon={Trash2} label={`${g.name} uit Nexus verwijderen`} onClick={() => run(() => api.removeGame(g.id))} />}</div> : <GameCard key={g.id} game={g} favorite={state.favorites.includes(g.id)} artwork={state.settings.artwork} onPlay={() => gameLaunch(g)} onFavorite={() => run(() => api.favorite(g.id))} onRemove={g.custom ? () => run(() => api.removeGame(g.id)) : null} />)}</div> : <Empty icon={Gamepad2} title={state.library.scanning ? 'We zoeken je werelden bij elkaar' : search || onlyFavorites || source !== 'Alle' ? 'Geen games gevonden' : 'Je bibliotheek staat klaar'} text={state.library.scanning ? 'Nexus doorzoekt je lokale launchers en Windows-installaties.' : search || onlyFavorites ? 'Probeer een andere zoekopdracht of wijzig je filters.' : 'Scan je pc op geïnstalleerde games of voeg een eigen game toe.'} action={state.library.scanning ? null : 'Game toevoegen'} onClick={() => setModal('add-game')} />}
    <div className="library-footnote"><ShieldCheck size={14} />Automatische detectie van lokale installaties. Niet-herkende games voeg je toe via een bestand of Windows-app.{state.library.scannedAt && <span>Laatste scan {new Date(state.library.scannedAt).toLocaleTimeString('nl-NL', { hour: '2-digit', minute: '2-digit' })}</span>}</div>
  </>;
}
function Apps({ state, run, goService }) { return <><div className="page-heading"><div><div className="eyebrow"><span className="tiny-line" /> YOUR PEOPLE. YOUR PLATFORMS.</div><h1>Alles blijft verbonden<span className="accent">.</span></h1><p>Je vertrouwde apps, met een eigen plek in Nexus.</p></div></div><div className="apps-grid">{Object.entries(state.services).map(([id, s]) => <section className="app-card" key={id}><div className="app-card-top"><AppMark id={id} color={s.color} size="large" /><span className="pill">WINDOWS APP</span></div><h2>{s.name}</h2><p>{id === 'discord' ? 'De echte Discord-app op je Nexus-scherm. Je bestaande account, servers en voice blijven beschikbaar.' : id === 'whatsapp' ? 'Gebruik de geïnstalleerde WhatsApp-app van Windows met je bestaande gesprekken en aanmelding.' : id === 'spotify' ? 'De geïnstalleerde Spotify-app, inclusief je eigen playlists, podcasts en offline bibliotheek.' : 'Open Xbox Cloud Gaming in je browser, of start de Xbox-app voor je pc-games en partyfuncties.'}</p><div className="app-card-actions"><button className="button primary" onClick={() => id === 'xbox' ? run(() => api.service('external', id)) : goService(id)}>{id === 'xbox' ? 'Desktopapp openen' : 'Open in Nexus'}<ArrowUpRight size={15} /></button></div></section>)}</div><section className="settings-section"><div className="section-title"><LayoutGrid size={18} /><div><h2>Alle launchers binnen handbereik</h2><p>Open je geïnstalleerde clients. Games start je rechtstreeks vanuit de bibliotheek.</p></div></div><div className="launcher-cards">{Object.keys(state.launchers).map(name => <button key={name} onClick={() => run(() => api.launcher(name))}><AppMark name={name} /><span>{name}</span><ArrowUpRight size={16} /></button>)}</div></section></>; }
function ServicePage({ id, definition, status, state, run }) {
  const target = useRef(); const externalOnly = id === 'xbox';
  useEffect(() => {
    if (externalOnly) return;
    let disposed = false;
    const resize = () => { if (target.current && !disposed) { const b = target.current.getBoundingClientRect(); api.serviceBounds({ x: b.x, y: b.y, width: b.width, height: b.height }).catch(() => {}); } };
    run(() => api.service('open', id)).then(resize);
    const observer = new ResizeObserver(resize); if (target.current) observer.observe(target.current);
    window.addEventListener('resize', resize);
    return () => { disposed = true; observer.disconnect(); window.removeEventListener('resize', resize); api.service('hide').catch(() => {}); };
  }, [id]);
  return <><div className="service-toolbar"><div><AppMark id={id} color={definition.color} /><span><h1>{definition.name}</h1><small>{externalOnly ? 'Windows-integratie' : 'Eigen Nexus-app · Sessie lokaal bewaard'}</small></span></div>
    <div>{!externalOnly && <><span className="session-badge"><ShieldCheck size={13} />Eigen sessie</span><IconButton icon={ArrowLeft} label="Terug in app" onClick={() => run(() => api.service('back', id))} /><IconButton icon={RefreshCw} label="App opnieuw laden" onClick={() => run(() => api.service('reload', id))} /></>}</div></div>
    <div ref={target} className="service-view">{externalOnly ? <div className="service-intro"><AppMark id={id} color={definition.color} size="large" /><h2>Een wereld aan games.</h2><p>Start de Xbox-app voor je games en party’s. Xbox Cloud Gaming opent in je browser.</p><button className="button primary" onClick={() => run(() => api.service('external', id))}>Xbox-app starten<ArrowUpRight size={16} /></button><button className="text-link" onClick={() => run(() => api.service('browser', id))}>Open Xbox Cloud Gaming<ExternalLink size={14} /></button></div>
    : status?.error || state.preview ? <Empty icon={Globe} title="De app kon niet worden geladen" text={state.preview ? 'Deze app werkt in de Nexus Hub-desktopapp.' : status.error || 'Controleer je verbinding en probeer opnieuw.'} action="Opnieuw proberen" onClick={() => run(() => api.service('reload', id))} />
    : <div className="service-loading"><RefreshCw size={25} className="spin" /><p>{definition.name} laden…</p></div>}</div></>;
}
function NativeServicePage({ id, definition, status, run, state }) {
  const target = useRef();
  useEffect(() => {
    let disposed = false;
    const resize = () => { if (!disposed && target.current) { const b = target.current.getBoundingClientRect(); api.serviceBounds({ x: b.x, y: b.y, width: b.width, height: b.height }).catch(() => {}); } };
    run(() => api.service('open', id)).then(resize);
    const observer = new ResizeObserver(resize); if (target.current) observer.observe(target.current);
    return () => { disposed = true; observer.disconnect(); api.service('hide').catch(() => {}); };
  }, [id]);
  return <><div className="service-toolbar"><div><AppMark id={id} color={definition.color} /><span><h1>{definition.name}</h1><small>Geïnstalleerde Windows-app · Bestaande aanmelding</small></span></div><div><span className="session-badge"><Monitor size={13} />Windows-app</span><button className="button secondary" onClick={() => run(() => api.service('external', id))}>Los openen<ExternalLink size={14} /></button><button className="button secondary" onClick={() => run(() => api.service('reload', id))}><RefreshCw size={15} />In Nexus plaatsen</button></div></div><div ref={target} className="service-view"><div className="service-intro native-app-card"><AppMark id={id} color={definition.color} size="large" /><h2>{status?.error ? definition.name + ' verbinden' : status?.loading ? 'Windows-app openen…' : definition.name + ' op je Nexus-scherm'}</h2><p>{state.preview ? 'Open Nexus Hub op Windows om je geïnstalleerde apps te gebruiken.' : status?.error || 'Nexus plaatst het echte appvenster in deze ruimte. Je aanmelding en gegevens blijven in de Windows-app. Bij afsluiten van Nexus wordt het venster teruggezet.'}</p>{status?.error && <button className="button primary" onClick={() => run(() => api.service('reload', id))}>Opnieuw proberen</button>}{status?.loading && <RefreshCw size={24} className="spin" />}</div></div></>;
}
function Settings({ state, changeSettings, run }) {
  const s = state.settings; const [name, setName] = useState(s.username);
  return <><div className="page-heading"><div><div className="eyebrow"><span className="tiny-line" /> BUILT AROUND YOU.</div><h1>Maak Nexus van jou<span className="accent">.</span></h1><p>Een tweede scherm dat precies bij je setup past.</p></div><span className="pill">NEXUS HUB {state.version}</span></div><div className="settings-grid">
    <section className="settings-section"><div className="section-title"><Monitor size={20} /><div><h2>Je scherm, jouw cockpit</h2><p>Nexus blijft op het gekozen scherm, ook bij herstart en in overlaymodus.</p></div></div><div className="display-lock-note"><ShieldCheck size={15} /><span>{state.displayTarget?.available === false ? `${state.displayTarget.label} is niet aangesloten. Je keuze blijft bewaard.` : `Vast scherm: ${state.displayTarget?.label || 'kies hieronder je display'}`}</span></div><div className="display-cards">{state.displays.length ? state.displays.map((d, i) => <button key={d.id} className={(state.displayTarget?.activeId ?? s.displayId) === d.id ? 'active' : ''} onClick={() => changeSettings({ displayId: d.id })}><div className="display-illustration"><Monitor size={46} strokeWidth={1} /><span>{i + 1}</span></div><strong>{d.label}</strong><small>{d.width} × {d.height}{d.primary ? ' · Hoofdscherm' : ' · Extra scherm'}</small>{(state.displayTarget?.activeId ?? s.displayId) === d.id && <Check size={15} />}</button>) : <p>Open de desktopapp om je beeldschermen te kiezen.</p>}</div><SettingRow label="Volledig scherm" description="Vul het gekozen scherm. F11 wisselt, Escape keert terug." checked={Boolean(state.fullscreen)} onChange={value => changeSettings({ fullscreen: value })} /><SettingRow label="Altijd op de voorgrond" description="Houd Nexus zichtbaar boven normale vensters." checked={s.alwaysOnTop} onChange={value => changeSettings({ alwaysOnTop: value })} /><button className="text-link" onClick={() => run(() => api.window('display-settings'))}>Windows-beeldscherminstellingen<ExternalLink size={14} /></button></section>
    <section className="settings-section"><div className="section-title"><Sparkles size={20} /><div><h2>De juiste sfeer</h2><p>Rustig, helder en helemaal jouw stijl.</p></div></div><div className="theme-options">{[['mint', 'Arctic mint', '#a7e6c7'], ['violet', 'After hours', '#c0adf1'], ['amber', 'Golden hour', '#eac08c']].map(([id, label, color]) => <button key={id} className={s.theme === id ? 'active' : ''} onClick={() => changeSettings({ theme: id })}><span className="theme-swatch" style={{ '--swatch': color }}><i /><i /><i /></span><span>{label}</span>{s.theme === id && <Check size={14} />}</button>)}</div><div className="setting-row"><div><strong>Weergavedichtheid</strong><p>Meer ruimte of meer informatie op je scherm.</p></div><select aria-label="Weergavedichtheid" className="select" value={s.density} onChange={e => changeSettings({ density: e.target.value })}><option value="comfortable">Comfortabel</option><option value="compact">Compact</option></select></div><SettingRow label="Minder animatie" description="Een stiller dashboard, zonder bewegende effecten." checked={s.reduceMotion} onChange={value => changeSettings({ reduceMotion: value })} /><SettingRow label="Gamehoezen ophalen" description="Toon automatisch gevonden en lokaal bewaarde hoezen. Kies ook zelf een afbeelding per game." checked={s.artwork} onChange={value => changeSettings({ artwork: value })} /></section>
    <section className="settings-section"><div className="section-title"><Settings2 size={20} /><div><h2>Dagelijks gebruik</h2><p>Kleine details die het verschil maken.</p></div></div><div className="setting-row"><div><strong>Hoe mogen we je noemen?</strong><p>Alleen opgeslagen op deze computer.</p></div><input className="text-input name-input" aria-label="Je naam" placeholder="Je voornaam" value={name} maxLength={36} onChange={e => setName(e.target.value)} onBlur={() => changeSettings({ username: name })} onKeyDown={e => { if (e.key === 'Enter') e.target.blur(); }} /></div><SettingRow label="Starten met Windows" description="Werkt zodra Nexus met de installer is geïnstalleerd." checked={s.autostart} onChange={value => changeSettings({ autostart: value })} /><div className="hotkeys"><div><span>Toon / verberg Nexus</span><kbd>Ctrl + Shift + Space</kbd></div><div><span>Compacte overlay</span><kbd>Ctrl + Shift + O</kbd></div><div><span>Zoeken in Nexus</span><kbd>Ctrl + K</kbd></div><div><span>Volledig scherm</span><kbd>F11</kbd></div></div></section>
    <section className="settings-section"><div className="section-title"><ShieldCheck size={20} /><div><h2>Lokaal en in jouw handen</h2><p>Geen Nexus-account. Geen telemetrie.</p></div></div><p className="settings-prose">Je indeling, notities en bibliotheek worden op deze pc opgeslagen. Discord, Spotify en WhatsApp gebruiken hun geïnstalleerde Windows-app en bestaande aanmelding. Nexus beheert hun vensters en zet ze bij afsluiten terug. Aanmelden en uitloggen doe je in de Windows-app zelf. Nexus leest geen wachtwoorden of chatberichten uit.</p><div className="settings-actions"><button className="button secondary" onClick={() => run(() => api.exportConfig()).then(done => done && null)}><Download size={15} />Indeling exporteren</button><button className="button secondary" onClick={() => run(() => api.importConfig())}><ArrowUp size={15} />Indeling importeren</button></div><p className="small-note">Een export bevat je thema, widgets en indeling. Accounts, games en notities blijven lokaal.</p><div className="settings-bottom"><span>Nexus Hub · Windows 10 / 11</span><button className="text-link danger" onClick={() => run(() => api.window('quit'))}><Power size={14} />Nexus afsluiten</button></div></section>
  </div></>;
}
function SettingRow({ label, description, checked, onChange }) { return <div className="setting-row"><div><strong>{label}</strong><p>{description}</p></div><button className={`toggle ${checked ? 'on' : ''}`} role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)} /></div>; }
function Modal({ title, onClose, children, wide }) {
  const ref = useRef();
  useEffect(() => { const before = document.activeElement; const focusable = () => [...(ref.current?.querySelectorAll('button:not([disabled]), input, select, textarea, [tabindex="0"]') || [])]; focusable()[0]?.focus(); const trap = e => { if (e.key !== 'Tab') return; const nodes = focusable(), first = nodes[0], last = nodes.at(-1); if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } }; ref.current?.addEventListener('keydown', trap); return () => { ref.current?.removeEventListener('keydown', trap); before?.focus(); }; }, []);
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><div className={`modal ${wide ? 'wide' : ''}`} role="dialog" aria-modal="true" aria-label={title} ref={ref}><div className="modal-heading"><div><span className="eyebrow">NEXUS WORKSPACE</span><h2>{title}</h2></div><IconButton icon={X} label="Venster sluiten" onClick={onClose} /></div><div className="modal-content">{children}</div></div></div>;
}
function WidgetPicker({ state, layout, updateLayout, run }) {
  const [webName, setWebName] = useState(''), [webUrl, setWebUrl] = useState('');
  return <><p className="modal-description">Kies wat je wilt zien in je {profiles[state.settings.profile]}-dashboard. Je kunt alles later verplaatsen.</p><div className="widget-catalog">{Object.entries(widgetInfo).map(([id, [name, Icon, description]]) => <button key={id} className={layout.includes(id) ? 'added' : ''} onClick={() => updateLayout(layout.includes(id) ? layout.filter(w => w !== id) : [...layout, id])}><div><span className="catalog-icon"><Icon size={22} strokeWidth={1.4} /></span><span className="catalog-check">{layout.includes(id) ? <Check size={15} /> : <Plus size={15} />}</span></div><strong>{name}</strong><p>{description}</p></button>)}</div><div className="web-widget-form"><div className="section-title"><Globe size={19} /><div><h3>Voeg je eigen webwidget toe</h3><p>Bijvoorbeeld een dashboard, agenda of je favoriete website.</p></div></div><form onSubmit={e => { e.preventDefault(); run(() => api.webWidget({ name: webName, url: webUrl })).then(result => { if (result) { setWebName(''); setWebUrl(''); } }); }}><input className="text-input" aria-label="Naam van webwidget" placeholder="Naam van je widget" value={webName} onChange={e => setWebName(e.target.value)} required maxLength={50} /><input className="text-input" type="url" aria-label="Website van webwidget" placeholder="https://…" value={webUrl} onChange={e => setWebUrl(e.target.value)} required pattern="https://.*" /><button className="button primary" type="submit"><Plus size={16} />Toevoegen</button></form>{state.webWidgets.map(w => <div className="custom-widget-row" key={w.id}><Globe size={16} /><span><strong>{w.name}</strong><small>{new URL(w.url).hostname}</small></span><button className="button ghost" onClick={() => updateLayout(layout.includes(w.id) ? layout.filter(id => id !== w.id) : [...layout, w.id])}>{layout.includes(w.id) ? 'Verbergen' : 'Toevoegen'}</button><IconButton icon={Trash2} label={`${w.name} verwijderen`} onClick={() => run(() => api.removeWebWidget(w.id))} /></div>)}</div></>;
}
function AddGame({ state, run, setModal, notify }) {
  const [query, setQuery] = useState('');
  const apps = state.library.startApps.filter(a => a.name.toLowerCase().includes(query.toLowerCase()) && /^[\w.!-]+$/.test(a.appId)).slice(0, 60);
  return <><button className="file-picker" onClick={() => run(() => api.addGame()).then(result => { if (result) { setModal(null); notify('Game toegevoegd aan je bibliotheek'); } })}><Plus size={25} /><span><strong>Kies een game of snelkoppeling</strong><small>Een .exe, .lnk of .url op je computer</small></span><ArrowRight size={18} /></button><div className="or-divider"><span>OF EEN WINDOWS-APP</span></div><label className="input-search"><Search size={17} /><input autoFocus placeholder="Zoek een geïnstalleerde Windows-app…" aria-label="Windows-app zoeken" value={query} onChange={e => setQuery(e.target.value)} /></label><div className="start-app-list">{apps.map(a => <button key={a.appId} onClick={() => run(() => api.addStartApp(a.appId)).then(result => { if (result) { setModal(null); notify(`${a.name} toegevoegd`); } })}><Gamepad2 size={18} /><span>{a.name}</span><Plus size={16} /></button>)}{!apps.length && <p className="small-note">Geen apps gevonden. Scan eerst je bibliotheek of kies een bestand.</p>}</div></>;
}
function CommandSearch({ state, navigate, goService, gameLaunch, setModal }) {
  const [query, setQuery] = useState('');
  const items = [
    { id: 'home', title: 'Dashboard', detail: 'Je command center', icon: LayoutDashboard, action: () => navigate('dashboard') },
    { id: 'games', title: 'Gamebibliotheek', detail: `${state.library.games.length} games`, icon: Gamepad2, action: () => navigate('library') },
    { id: 'settings', title: 'Instellingen', detail: 'Schermen, thema’s en voorkeuren', icon: Settings2, action: () => navigate('settings') },
    ...Object.entries(state.services).map(([id, s]) => ({ id, title: s.name, detail: 'App openen', icon: serviceIcons[id], action: () => goService(id) })),
    ...state.library.games.map(g => ({ id: g.id, title: g.name, detail: g.source, icon: Gamepad2, action: () => { gameLaunch(g); setModal(null); } })),
    ...state.webWidgets.map(w => ({ id: w.id, title: w.name, detail: 'Webwidget', icon: Globe, action: () => goService(w.id) })),
  ].filter(i => `${i.title} ${i.detail}`.toLowerCase().includes(query.toLowerCase())).slice(0, 20);
  return <><label className="input-search command-input"><Search size={20} /><input autoFocus placeholder="Zoek games, apps of instellingen…" aria-label="Zoek in Nexus" value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') items[0]?.action(); }} /></label><div className="command-results">{items.map(({ id, title, detail, icon: Icon, action }) => <button key={id} onClick={action}><Icon size={19} /><span><strong>{title}</strong><small>{detail}</small></span><ArrowUpRight size={16} /></button>)}{!items.length && <Empty compact icon={Search} title="Niets gevonden" text="Probeer een andere zoekopdracht." />}</div></>;
}



