import React, { useEffect, useRef, useState } from 'react';
import { Activity, ArrowDown, ArrowUp, Check, Cpu, ExternalLink, Fan, HardDrive, Lightbulb, Music2, Pause, Play, Plus, Radio, RefreshCw, Search, Star, Thermometer, Volume2, X, Zap } from 'lucide-react';
import { api } from './api.js';
import './extensions.css';
const number = (value, unit = '', digits = 0) => value == null || !Number.isFinite(value) ? '—' : `${value.toFixed(digits)}${unit}`;
const bytes = value => value == null ? '—' : `${(value / 1024 ** 3).toFixed(1)} GB`;
function Reading({ title, value, sub }) { return <div className="sensor-reading"><span>{title}</span><strong>{value}</strong>{sub && <small>{sub}</small>}</div>; }
export function HardwarePage({ metrics }) {
  const hardware = metrics.hardware; const info = hardware?.info || {};
  const sensorUnit = { Temperature: ' °C', Fan: ' RPM', Voltage: ' V', Power: ' W', Load: '%', Clock: ' MHz', Data: ' GB', SmallData: ' MB', Throughput: ' B/s', Control: '%' };
  return <><div className="page-heading"><div><div className="eyebrow">LIVE HARDWARE</div><h1>Inzicht in je systeem<span className="accent">.</span></h1><p>CPU, videokaarten, geheugen, opslag en sensoren op één scherm.</p></div><span className="pill">{hardware ? `Bijgewerkt ${new Date(hardware.at).toLocaleTimeString('nl-NL')}` : 'Bronnen verbinden…'}</span></div>
    <div className="hardware-grid"><section className="extension-card span-full"><div className="extension-title"><Cpu /><div><h2>{metrics.cpuName || 'Processor'}</h2><p>{info.board ? `${info.board.manufacturer} ${info.board.model}` : 'Windows-prestaties'}</p></div><span className="pill">CPU</span></div><div className="sensor-row"><Reading title="Belasting" value={number(metrics.cpu, '%')} /><Reading title="Kloksnelheid" value={number(hardware?.cpu.speed, ' GHz', 2)} /><Reading title="Temperatuur" value={number(hardware?.cpu.temperature ?? hardware?.sensors.find(s => s.type === 'Temperature' && /cpu/i.test(s.parent) && /package|tctl|average/i.test(s.name))?.value, ' °C')} sub="— betekent niet beschikbaar" /><Reading title="Threads" value={metrics.cores || '—'} /></div><div className="core-grid">{hardware?.cpu.cores.map((load, index) => <div key={index} title={`Thread ${index + 1}: ${number(load, '%')}`}><span>{index + 1}</span><div><i style={{ width: `${load}%` }} /></div><small>{number(load, '%')}</small></div>)}</div></section>
    {(hardware?.gpus || []).map((gpu, index) => <section key={gpu.id || index} className="extension-card"><div className="extension-title"><Activity /><div><h2>{gpu.name}</h2><p>{gpu.source}{gpu.driver ? ` · Driver ${gpu.driver}` : ''}</p></div></div><div className="sensor-row"><Reading title="Belasting" value={number(gpu.usage, '%')} /><Reading title="Temperatuur" value={number(gpu.temperature, ' °C')} /><Reading title="Ventilator" value={number(gpu.fan, '%')} /><Reading title="Vermogen" value={number(gpu.power, ' W', 1)} /><Reading title="GPU-klok" value={number(gpu.clock, ' MHz')} /><Reading title="Geheugenklok" value={number(gpu.memoryClock, ' MHz')} /><Reading title="Videogeheugen" value={gpu.memoryUsed == null ? '—' : `${(gpu.memoryUsed / 1024).toFixed(1)} / ${(gpu.memoryTotal / 1024).toFixed(1)} GB`} /><Reading title="Vermogenslimiet" value={number(gpu.powerLimit, ' W')} /></div></section>)}
    <section className="extension-card"><div className="extension-title"><Activity /><h2>Werkgeheugen</h2></div><div className="sensor-row"><Reading title="In gebruik" value={bytes(metrics.ramUsed)} /><Reading title="Totaal" value={bytes(metrics.ramTotal)} /><Reading title="Vrij" value={metrics.ramTotal ? bytes(metrics.ramTotal - metrics.ramUsed) : '—'} /></div>{info.memory?.map((m, i) => <div className="hardware-line" key={i}><span>{m.bank || `Module ${i + 1}`} · {m.manufacturer}</span><strong>{bytes(m.size)} · {m.type} · {m.clock || '—'} MHz</strong></div>)}</section>
    <section className="extension-card"><div className="extension-title"><HardDrive /><h2>Opslag</h2></div>{hardware?.disks.map(d => <div className="storage-reading" key={d.name}><div><strong>{d.name}</strong><span>{bytes(d.used)} / {bytes(d.size)}</span></div><div className="hardware-meter"><i style={{ width: `${d.percent}%` }} /></div></div>)}{info.storage?.map((d, i) => <div className="hardware-line" key={i}><span>{d.name} · {d.type} · {d.interface}</span><strong>{d.smartStatus || 'SMART onbekend'}</strong></div>)}</section>
    <section className="extension-card"><div className="extension-title"><Zap /><h2>Netwerkinterfaces</h2></div>{hardware?.networks.map((n, i) => <div className="hardware-line" key={i}><span>{n.name}<small>{n.state}</small></span><strong>↓ {n.down >= 0 ? number(n.down / 1024, ' KB/s') : '—'} · ↑ {n.up >= 0 ? number(n.up / 1024, ' KB/s') : '—'}</strong></div>)}<p className="extension-note">Alle actieve interfaces; het dashboard toont de Windows-netwerkmeting.</p></section>
    {!!hardware?.adapters.length && <section className="extension-card span-full"><div className="extension-title"><Activity /><h2>Windows GPU-engines</h2></div><p className="extension-note">Windows-adapters op hun eigen teller-ID; de driver koppelt deze niet altijd aan een modelnaam.</p><div className="sensor-row">{hardware.adapters.map((adapter, i) => <Reading key={adapter.id} title={`Adapter ${i + 1} · ${adapter.id}`} value={number(adapter.usage, '%')} sub={`Dedicated ${bytes(adapter.dedicated)} · Shared ${bytes(adapter.shared)}`} />)}</div><div className="engine-grid">{hardware.adapters.flatMap((adapter, i) => Object.entries(adapter.engines).map(([name, value]) => <div key={`${adapter.id}-${name}`}><span>GPU {i + 1} · {name}</span><strong>{number(value, '%')}</strong></div>))}</div></section>}
    <section className="extension-card span-full"><div className="extension-title"><Thermometer /><h2>Extra sensoren</h2><span className="pill">{hardware?.sensors.length || 0} SIGNALEN</span></div>{hardware?.sensors.length ? <div className="sensor-row">{hardware.sensors.map((s, i) => <Reading key={i} title={s.name} value={number(s.value, sensorUnit[s.type] || ` ${s.type}`, ['Voltage', 'Power'].includes(s.type) ? 2 : 1)} sub={`${s.source} · ${s.parent}`} />)}</div> : <p className="extension-note">Start LibreHardwareMonitor of OpenHardwareMonitor met WMI ingeschakeld om beschikbare CPU-, moederbord-, fan- en spanningssensoren toe te voegen. Niet elke sensor wordt door elke driver vrijgegeven.</p>}</section>
    <section className="extension-card span-full"><div className="extension-title"><Check /><h2>Databronnen</h2></div><div className="source-health">{hardware?.sources.map(source => <div key={source.name}><i className={`status-dot ${source.available ? '' : 'neutral'}`} /><span><strong>{source.name}</strong><small>{source.detail}</small></span><b>{source.available ? 'Verbonden' : 'Niet beschikbaar'}</b></div>)}</div></section></div>
  </>;
}

export function RGBPage({ run }) {
  const [data, setData] = useState(null), [selected, setSelected] = useState([]), [color, setColor] = useState('#85dbc1'), [brightness, setBrightness] = useState(70), [busy, setBusy] = useState(false), [results, setResults] = useState([]);
  const refresh = async () => { setBusy(true); const next = await run(() => api.rgbStatus()); if (next) { setData(next); setSelected(old => old.filter(id => next.devices.some(d => d.id === id))); } setBusy(false); };
  useEffect(() => { refresh(); }, []);
  const apply = async value => { setBusy(true); const response = await run(() => api.rgbApply({ ids: selected, color, brightness: value })); if (response) setResults(response); setBusy(false); };
  return <><div className="page-heading"><div><div className="eyebrow">ONE SETUP. ONE COLOUR.</div><h1>Jouw licht, overal<span className="accent">.</span></h1><p>Bedien compatibele MSI-, Corsair- en GIGABYTE-verlichting vanaf één plek.</p></div><button className="button secondary" disabled={busy} onClick={refresh}><RefreshCw size={16} className={busy ? 'spin' : ''} />Apparaten zoeken</button></div>
    <div className="rgb-layout"><section className="extension-card rgb-control"><div className="rgb-orbit" style={{ '--rgb-color': color, opacity: .35 + brightness / 155 }}><Lightbulb size={48} strokeWidth={1} /></div><h2>Eén kleur voor je setup</h2><label className="rgb-color-label">Kleur<input aria-label="RGB-kleur" type="color" value={color} onChange={e => setColor(e.target.value)} /><code>{color.toUpperCase()}</code></label><div className="rgb-swatches">{['#85dbc1', '#ab8cf5', '#ffc36b', '#ff5577', '#63baff', '#ffffff'].map(c => <button key={c} aria-label={`Kleur ${c}`} style={{ background: c }} onClick={() => setColor(c)} />)}</div><label className="rgb-brightness">Helderheid <strong>{brightness}%</strong><input aria-label="RGB-helderheid" type="range" min="0" max="100" value={brightness} onChange={e => setBrightness(+e.target.value)} /></label><button className="button primary" disabled={busy || !selected.length} onClick={() => apply(brightness)}><Lightbulb size={16} />Toepassen op {selected.length} apparaten</button><button className="button secondary" disabled={busy || !selected.length} onClick={() => apply(0)}>Verlichting uit</button><p className="extension-note">Statische verlichting. Alleen geselecteerde apparaten wijzigen; pas één controller per fysiek apparaat toe.</p></section>
    <div className="rgb-devices"><section className="extension-card"><div className="extension-title"><Zap /><h2>Apparaten en zones</h2></div>{data?.devices.length ? data.devices.map(device => <label className="rgb-device" key={device.id}><input type="checkbox" checked={selected.includes(device.id)} onChange={() => setSelected(old => old.includes(device.id) ? old.filter(id => id !== device.id) : [...old, device.id])} /><span><strong>{device.name}</strong><small>{device.provider} · {device.leds} leds/zones</small></span><Lightbulb size={18} /></label>) : <div className="extension-empty"><Lightbulb size={34} /><h3>{busy ? 'RGB-bronnen verbinden…' : 'Nog geen bedienbare apparaten'}</h3><p>Controleer de verbindingen hieronder. Je bestaande verlichting blijft actief.</p></div>}{results.map(result => <div className={`rgb-result ${result.ok ? '' : 'failed'}`} key={result.id}>{result.ok ? <Check size={15} /> : <X size={15} />}<span>{data?.devices.find(d => d.id === result.id)?.name}: {result.detail}</span></div>)}</section>
    <section className="extension-card"><div className="extension-title"><Activity /><h2>Verbindingen</h2></div>{data?.providers.map(provider => <div className="rgb-provider" key={provider.id}><div><i className={`status-dot ${provider.available ? '' : 'neutral'}`} /><strong>{provider.name}</strong><span>{provider.available ? 'Verbonden' : 'Instellen'}</span></div><p>{provider.detail}</p>{provider.id === 'msi' && !provider.available && <button className="button secondary" disabled={busy} onClick={async () => { setBusy(true); await run(() => api.rgbInstallMsi()); setBusy(false); refresh(); }}>Officiële MSI SDK ophalen</button>}<button className="text-link" onClick={() => run(() => api.rgbOpen(provider.id))}>{provider.id === 'openrgb' ? 'OpenRGB downloaden / informatie' : 'Fabrikantapp openen'}<ExternalLink size={13} /></button></div>)}<button className="text-link" onClick={() => run(() => api.rgbOpen('gigabyte'))}>GIGABYTE Control Center openen<ExternalLink size={13} /></button></section></div></div>
  </>;
}

export function useRadio() {
  const audio = useRef(null), [current, setCurrent] = useState(null), [playing, setPlaying] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState(''), [volume, setVolume] = useState(40);
  useEffect(() => {
    const player = new Audio(); player.preload = 'none'; player.volume = .4; audio.current = player;
    player.onplaying = () => { setPlaying(true); setLoading(false); setError(''); };
    player.onpause = () => { setPlaying(false); setLoading(false); };
    player.onwaiting = () => setLoading(true);
    player.onerror = () => { setError('Deze stream is niet bereikbaar of het audioformaat wordt niet ondersteund. Probeer opnieuw of kies een andere zender.'); setPlaying(false); setLoading(false); };
    return () => { player.pause(); player.removeAttribute('src'); player.load(); audio.current = null; };
  }, []);
  useEffect(() => { if (audio.current) audio.current.volume = volume / 100; }, [volume]);
  const play = station => {
    if (!audio.current) return; setError(''); setLoading(true); setCurrent(station);
    audio.current.src = station.url; audio.current.load();
    audio.current.play().catch(error => { if (error.name !== 'AbortError') { setError('Afspelen mislukt. Controleer de stream of je verbinding.'); setLoading(false); } });
    if ('mediaSession' in navigator) { navigator.mediaSession.metadata = new MediaMetadata({ title: station.name, artist: 'Nexus Internetradio' }); }
  };
  const stop = () => { audio.current?.pause(); if (audio.current) { audio.current.removeAttribute('src'); audio.current.load(); } setPlaying(false); setLoading(false); };
  const toggle = () => playing || loading ? stop() : current && play(current);
  useEffect(() => { if (!('mediaSession' in navigator)) return; navigator.mediaSession.setActionHandler('play', () => current && play(current)); navigator.mediaSession.setActionHandler('pause', stop); navigator.mediaSession.setActionHandler('stop', stop); navigator.mediaSession.playbackState = playing ? 'playing' : 'paused'; }, [current, playing]);
  return { current, playing, loading, error, volume, setVolume, play, toggle, stop };
}
export function RadioDock({ player, onOpen }) {
  if (!player.current) return null;
  return <div className="radio-dock"><Radio size={17} /><button className="radio-dock-title" onClick={onOpen}><strong>{player.current.name}</strong><small>{player.error ? 'Stream niet beschikbaar' : player.loading ? 'Verbinden…' : player.playing ? 'LIVE RADIO' : 'Gepauzeerd'}</small></button><button className="icon-button" aria-label={player.playing || player.loading ? 'Radio pauzeren' : 'Radio afspelen'} onClick={player.toggle}>{player.playing || player.loading ? <Pause size={18} /> : <Play size={18} />}</button><Volume2 size={15} /><input type="range" aria-label="Radiovolume" min="0" max="100" value={player.volume} onChange={e => player.setVolume(+e.target.value)} /></div>;
}
export function RadioPage({ state, run, player }) {
  const [name, setName] = useState(''), [country, setCountry] = useState('NL'), [tag, setTag] = useState(''), [results, setResults] = useState([]), [busy, setBusy] = useState(false), [error, setError] = useState(''), [onlyFavorites, setOnlyFavorites] = useState(false), [custom, setCustom] = useState(false), [customName, setCustomName] = useState(''), [url, setUrl] = useState('');
  const search = async e => { e?.preventDefault(); setBusy(true); setError(''); try { setResults(await api.radioSearch({ name, country, tag })); } catch { setError('De catalogus is niet bereikbaar. Je opgeslagen zenders kun je wel gebruiken.'); } finally { setBusy(false); } };
  useEffect(() => { search(); }, []);
  const favorites = state.radioFavorites || []; const stations = onlyFavorites ? favorites : results;
  return <><div className="page-heading"><div><div className="eyebrow">NEXUS FREQUENCIES</div><h1>Een wereld aan radio<span className="accent">.</span></h1><p>Ontdek livezenders. Je muziek speelt door terwijl je Nexus gebruikt.</p></div><button className="button secondary" onClick={() => setCustom(!custom)}><Plus size={16} />Eigen stream</button></div>
    <section className="radio-hero"><div className={`radio-visual ${player.playing ? 'playing' : ''}`}><Radio size={54} strokeWidth={1} /><div /><div /></div><div><span className="pill">{player.playing ? 'LIVE UITZENDING' : 'JOUW RADIO'}</span><h2>{player.current?.name || 'Vind je frequentie.'}</h2><p>{player.current ? `${player.current.country || 'Internetradio'} · ${player.current.codec || 'Audiostream'}` : 'Van lokale favorieten tot nieuwe ontdekkingen.'}</p>{player.current && <button className="button primary" onClick={player.toggle}>{player.playing || player.loading ? <Pause size={16} /> : <Play size={16} />}{player.loading ? 'Verbinden…' : player.playing ? 'Pauzeren' : 'Afspelen'}</button>}</div><div className="radio-volume"><Volume2 size={20} /><input type="range" aria-label="Volume internetradio" min="0" max="100" value={player.volume} onChange={e => player.setVolume(+e.target.value)} /><strong>{player.volume}%</strong></div></section>
    {player.error && <div className="info-banner">{player.error}</div>}
    {custom && <form className="extension-card radio-custom" onSubmit={async e => { e.preventDefault(); const saved = await run(() => api.radioFavorite({ name: customName, url })); if (saved) { setCustom(false); setOnlyFavorites(true); setCustomName(''); setUrl(''); } }}><h2>Eigen radiozender</h2><p className="extension-note">Gebruik een rechtstreeks MP3-, AAC-, OGG- of FLAC-streamadres; geen website of afspeellijst.</p><input className="text-input" aria-label="Zendernaam" placeholder="Naam van de zender" required value={customName} onChange={e => setCustomName(e.target.value)} /><input className="text-input" aria-label="Streamadres" placeholder="https://…/stream.mp3" type="url" required value={url} onChange={e => setUrl(e.target.value)} /><button className="button primary" type="submit">Bewaar zender</button></form>}
    <form className="radio-search" onSubmit={search}><label className="input-search"><Search size={17} /><input aria-label="Radiozender zoeken" placeholder="Zoek een zender…" value={name} onChange={e => setName(e.target.value)} /></label><select className="select" aria-label="Land" value={country} onChange={e => setCountry(e.target.value)}><option value="">Wereldwijd</option><option value="NL">Nederland</option><option value="BE">België</option><option value="DE">Duitsland</option><option value="GB">Verenigd Koninkrijk</option><option value="US">Verenigde Staten</option></select><select className="select" aria-label="Radiogenre" value={tag} onChange={e => setTag(e.target.value)}><option value="">Alle genres</option>{['pop', 'rock', 'dance', 'jazz', 'classical', 'ambient', 'news'].map(g => <option key={g}>{g}</option>)}</select><button className="button primary" disabled={busy}>{busy ? <RefreshCw size={16} className="spin" /> : <Search size={16} />}Zoeken</button></form>
    <div className="source-tabs"><button className={!onlyFavorites ? 'active' : ''} onClick={() => setOnlyFavorites(false)}>Ontdekken <span>{results.length}</span></button><button className={onlyFavorites ? 'active' : ''} onClick={() => setOnlyFavorites(true)}>Favorieten <span>{favorites.length}</span></button></div>{error && <div className="info-banner">{error}</div>}
    <div className="radio-stations">{stations.map(station => <article className={`radio-station ${player.current?.id === station.id ? 'active' : ''}`} key={station.id}><button className="station-play" aria-label={`${station.name} afspelen`} onClick={() => player.play(station)}><Play size={20} /></button><div><h3>{station.name}</h3><p>{station.country || 'Eigen stream'} · {station.codec || 'Radio'}{station.bitrate ? ` · ${station.bitrate} kbps` : ''}</p><small>{station.tags}</small></div><button className="icon-button" aria-label={`${station.name} favoriet`} onClick={() => run(() => api.radioFavorite(station))}><Star size={18} fill={favorites.some(s => s.id === station.id) ? 'currentColor' : 'none'} /></button></article>)}</div>{!busy && !stations.length && <div className="extension-empty"><Radio size={32} /><h3>{onlyFavorites ? 'Je favoriete zenders komen hier' : 'Geen zenders gevonden'}</h3><p>{onlyFavorites ? 'Tik op de ster bij een zender of voeg je eigen stream toe.' : 'Probeer een andere naam, land of genre.'}</p></div>}<p className="extension-note">Zendercatalogus: Radio Browser. Beschikbaarheid en geluidskwaliteit worden door de zender bepaald. Geen automatisch afspelen bij opstarten.</p>
  </>;
}
